# spring configuration
spring:
  application:
    name: client-springboot
  profiles:
    active: development


---
# configuration: default(common)
spring:
  data:
    redis:
      connect-timeout: 5s
      timeout: 5s

      lettuce:
        pool:
          enabled: false
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1ms
          time-between-eviction-runs: 30s



---
# configuration: development
spring:
  config:
    activate:
      on-profile: development

  data:
    redis:
      host: localhost
      port: 6379
#      username: default
#      password: secret


---
# configuration: production
spring:
  config:
    activate:
      on-profile: production
